name: built_firebase
description: Serializers and built values for services inherent to firebase ( cloud firestore | messaging )
version: 0.0.1
repository: https://github.com/BreX900/flutter_value_bloc/tree/master/value_bloc
issue_tracker: https://github.com/BreX900/flutter_value_bloc/issues
homepage: https://github.com/BreX900/flutter_value_bloc/

# flutter pub publish --dry-run

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  built_collection: ^4.3.2
  built_value: ^7.1.0

  cloud_firestore: ^0.14.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  analyzer: ^0.39.14

  # flutter packages pub run build_runner build --delete-conflicting-outputs
  # flutter packages pub run build_runner watch --delete-conflicting-outputs
  build_runner: ^1.10.2
  built_value_generator: ^7.1.0

  test: ^1.15.7